### ISSUE TITLE
Consider adding Quasar to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [Technik97/Quasar#1]
Hey @Technik97, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by Technik97** [comment]
> Hey @Technik97, feel free to submit a PR to showcase your project!

Hi @billy1624 , I would love to showcase my project, also really enjoying using SeaOrm.

**Comment by billy1624** [comment]
Thanks for the support!

**Comment by Technik97** [comment]
Added to community.md

**Comment by billy1624** [comment]
Thanks! @Technik97
